


name: Workflow for master/development branches

on:
  pull_request:
  push:
    branches:
      - 'development'
      - 'master'


jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Tests
        run: bash ./gradlew test --stacktrace  
  apk:
    name: Generate APK
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: Calculator
          path: app/build/outputs/apk/debug/Calculator.apk



  lintCheck:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Static Analysis
        run: ./gradlew lint

      - name: Upload Static Analysis Report For Calculator Module
        uses: actions/upload-artifact@v2.2.1
        if: failure()
        with:
          name: Static Analysis Report
          path: app/build/apk/debug/Calculator.apk

  pmd:
    name: PMD
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: PMD Check
        run: ./gradlew pmd

      - name: Upload PMD Report
        uses: actions/upload-artifact@v2.2.1
        if: failure()
        with:
          name: PMD Report
          path: app/build/apk/debug/Calculator.apk
